language: python
python: 2.7
install:
  # Build/test dependencies
  - pip install -r requirements.txt
before_script:
  # Install Google App Engine SDK
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.24.zip -nv
  - unzip -q google_appengine_1.9.24.zip
script: py.test
notifications:
  email: 
    - maxime@werlen.fr
    #- caillolj@gmail.com
